export const INCREMENT_COUNTER = "INCREMENT_COUNTER"
export const DECREMENT_COUNTER = "DECREMENT_COUNTER"

export const ADDTOCART = "ADDTOCART"
export const INCREMENT_QTY = "INCREMENT_QTY"
export const DECREMENT_QTY = "DECREMENT_QTY"
export const DELETE_QTY = "DELETE_QTY"